# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-prom_serv'
    scrape_interval: '10s'
    static_configs:
    - targets: ['localhost:9100']

  - job_name: 'node-zabbix'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.15.42:9100']

  - job_name: 'node-egn_mon_vm'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.15.44:9100']

  - job_name: 'wmi-test-egndtco01'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.23.86:9182']

  - job_name: 'EGN-WS-8RVHZL2'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.10.122:9182']

  - job_name: 'EGN-WS-VSOM1'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.10.95:9182']

  - job_name: 'EGN-WS-VSOM2'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.10.97:9182']

  - job_name: 'EGN-RDS3'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.11.133:9182']

  - job_name: 'node_daemon'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.15.46:9100']

  - job_name: 'node_cpam'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.51.102:9100']

  - job_name: 'EGN-RDS4'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.11.62:9182']

  - job_name: 'EGN-RDS6'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.11.168:9182']

  - job_name: 'EGNWS1T'
    scrape_interval: '10s'
    static_configs:
    - targets: ['10.0.11.139:9182']
